### ISSUE TITLE
aspectj编译问题。

### ISSUE THREAD

**Issue by qihigh** [1170762202/WanAndroid#11]
我这边编译的时候总是通不过，会报错。
执行.\gradlew.bat clean assembleDebug
报错
![image](https://user-images.githubusercontent.com/1587551/101117293-a5e4fb80-3621-11eb-9ec0-d194bf23cea3.png)

但是在 项目 app 下的build.gradle添加
`aspectjx {
    //关闭AspectJX功能
    enabled false
}`
然后就能编译通过，
在把build.gradle的修改恢复，再次编译` .\gradlew.bat assembleDebug`能够成功打包运行，

每次只要clean一次，就需要开关一下aspectj

可能是什么原因呢？作者有没有遇到过？

环境：
![image](https://user-images.githubusercontent.com/1587551/101117540-2572ca80-3622-11eb-8045-48824f4a2967.png)

**Comment by 1170762202** [comment]
It didn't happened again , try Invalidate caches & Restart

**Comment by 1170762202** [comment]
AndroidStudio:4.0.1

**Comment by 1170762202** [comment]
AndroidStudio:4.0.1
classpath "com.android.tools.build:gradle:4.0.1"
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by qihigh** [comment]
thanks, 我研究研究AspectJX。
